<section class="section1"><h1>Lab week 3</h1>
<p>In week 2 we introduced lists and looked at <code>for</code> loops.</p>
<section class="section2"><h2>Script</h2>
<p>Last time we saw lists. A list contains many objects. Likewise, there are many mathematical things that contain many objects.</p>
<p>Sets are one type. If you add a set to another set you get a new set containing the objects in both sets. The new set is larger (generically) than either individual set.</p>
<p>Vectors are another type. If you add one vector to another vector you get a new vector whose components are the sum of the individual vector components. The new vector has the same size (in terms of number of components) as the individual vectors.</p>
<p>How does a list act?</p>
</section></section>

In [ ]:
list_1 = [1, 2]
list_2 = [3, 4]
print(list_1 + list_2)

In [ ]:
[1, 2, 3, 4]


<p>A list acts like the description of a set, not like a vector.</p>
<p>Consider what multiplying a container by a scalar number should do for a set and a vector. Then check a list:</p>

In [ ]:
print(2 * list_1)

In [ ]:
[1, 2, 1, 2]


<p>Again, lists act more like sets than vectors.</p>
<p>This is fine when we want to work with general sets. However, we will also frequently need (as in Linear Algebra) vectors, and matrices, and so on. In Python, we can use <code>numpy</code> for this: in particular we can use its <code>array</code> object. These can be created directly from lists.</p>

In [ ]:
import numpy
vector_1 = numpy.array(list_1)
vector_2 = numpy.array(list_2)
print(vector_1)
print(vector_1 + vector_2)
print(2 * vector_1)

In [ ]:
[1 2]
[4 6]
[2 4]


<p>We see that an <code>array</code> is displayed much like a list (using spaces rather than commas to separate entries). However, it acts as a vector would: addition of a pair of two-dimensional vectors produces another two-dimensional vector, as does multiplication of a two-dimensional vector by a scalar.</p>
<p>Note that the <code>len</code> function and the indexing operations act the same as on lists:</p>

In [ ]:
print(len(vector_1))
print(vector_1[0])

In [ ]:
2
1



In [ ]:
numbers = [1, 2, 3, 4, 5]
vector_n = numpy.array(numbers)
print(vector_n)
print(vector_n[-1])
print(vector_n[1:4])

In [ ]:
[1 2 3 4 5]
5
[2 3 4]


<p>There are some restrictions with <code>numpy</code> arrays. They are meant to represent vectors, matrices, and similar higher dimensional objects. So if you nest lists within lists you must do so consistently:</p>

In [ ]:
matrix_wrong_1 = numpy.array([1, 2, [3, 4]])

In [ ]:
---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-6-ce621beadb7d> in <module>()
----> 1 matrix_wrong_1 = numpy.array([1, 2, [3, 4]])


ValueError: setting an array element with a sequence.



In [ ]:
matrix_right_1 = numpy.array([[1, 2], [3, 4]])
print(matrix_right_1)

In [ ]:
[[1 2]
 [3 4]]


<p>You should also use only a single type of object in a <code>numpy</code> <code>array</code>: do not mix numbers with strings, for example.</p>
<p>With higher dimensional objects like matrices you can access them in two ways. Either use the "list of lists" approach:</p>

In [ ]:
print(matrix_right_1[0][0])

In [ ]:
1


<p>The alternative, which is preferred, is to treat it as a single object that takes multiple indexes:</p>

In [ ]:
print(matrix_right_1[0, 0])

In [ ]:
1


<p>Slicing works with higher dimensional objects:</p>

In [ ]:
print(matrix_right_1[:, 0])
print(matrix_right_1[1, :])

In [ ]:
[1 3]
[3 4]


<p>There are a number of utility functions for creating matrices:</p>

In [ ]:
print(numpy.ones(3))
print(numpy.ones([2, 2]))
print(numpy.zeros([2, 2]))
print(numpy.identity(3))
print(numpy.random.rand(2, 2))

In [ ]:
[ 1.  1.  1.]
[[ 1.  1.]
 [ 1.  1.]]
[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.11645041  0.82370944]
 [ 0.69588563  0.87133502]]


<p>Note that the conventions of the functions are not always consistent.</p>
<section class="section5"><h5>Exercise</h5>
<p>In the Gaussian Elimination algorithm a matrix (or augmented matrix) is reduced to triangular form by subtracting rows from each other. Write a function <code>row_elimination</code> that takes a matrix <code>A</code> and two row numbers <code>r1</code> and <code>r2</code>. It should return the matrix <code>A</code> with <span>$\epsilon \times$</span>
<code>r1</code> subtracted from row <code>r2</code>. Here <code>epsilon</code> should make the matrix entry <span>$a_{r_2, r_1} \to 0$</span>: that is,
<span>$
  \epsilon = \frac{a_{r_2, r_1}}{a_{r_1, r_1}}.
$</span>
</p>
<p>Check on the matrix
<span>$
A = \begin{pmatrix}
1 &amp; 4 &amp; 3 \\
2 &amp; -7 &amp; 5 \\
1 &amp; 2 &amp; 6
\end{pmatrix}.
$</span>
Can you use or extend your function to write a function that takes <code>A</code> and returns the triangular form?</p>
<p>The <code>numpy</code> package also contains a lot of useful Linear Algebra functions in its <code>linalg</code> subpackage. For example, matrix multiplication and dot products:</p>
</section>

In [ ]:
A = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
B = numpy.array([[7, 3, 1], [6, 1, 2], [3, 5, 2]])
d = numpy.array([5, 3, 1])

print(numpy.dot(A, B))
print(numpy.dot(A, d))
print(numpy.dot(d, d))

In [ ]:
[[28 20 11]
 [76 47 26]
 [97 29 23]]
[14 41 59]
35


<p>Computing determinants:</p>

In [ ]:
print(numpy.linalg.det(A))

In [ ]:
27.0


<p>Solving linear systems of equations, such as <span>$A {\bf x} = {\bf d}$</span>:</p>

In [ ]:
print(numpy.linalg.solve(A, d))

In [ ]:
[ -6.33333333e+00   5.66666667e+00  -1.40980702e-16]


<section class="section5"><h5>Exercise</h5>
<p>Define three matrices:
<span>$
A = \begin{pmatrix}
1 &amp; 4 &amp; 3 &amp; 2 \\
2 &amp; -7 &amp; 5 &amp; 1 \\
1 &amp; 2 &amp; 6 &amp; 0 \\
2 &amp; -10 &amp; 3 &amp; 4
\end{pmatrix}, \quad
B = \begin{pmatrix}
5 &amp; 2 &amp; -4 &amp; -2 \\
-3 &amp; 1 &amp; 5 &amp; 1 \\
4 &amp; -1 &amp; 1 &amp; 3 \\
2 &amp; 1 &amp; -1 &amp; 1
\end{pmatrix}, \quad
C = \begin{pmatrix}
3 &amp; 0 &amp; 0 &amp; 0 \\
7 &amp; -6 &amp; 0 &amp; 0 \\
2 &amp; -1 &amp; -1 &amp; 0 \\
-4 &amp; -2 &amp; 2 &amp; -2
\end{pmatrix}.
$</span>
Compute the ranks of all matrices. Compute the determinants of
<span>$
A^T B^{-1}, \qquad B/4, \qquad C, \qquad 2 B + C.
$</span>
</p>
</section>